### ISSUE TITLE
Invalid variable access: knex

### ISSUE THREAD

**Issue by ashwinvandijk** [felixmosh/knex-mock-client#1]
Thank you for your work so far, this library looks like exactly what I need. However, when I try the example from the readme, I get an error:

```The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables. Invalid variable access: knex```

Is there some configuration I'm missing? I can fix that error by using
```
jest.mock('../../knex', () => {
    const knex = require('knex');
    const mockKnexClient = require('knex-mock-client');
    return knex({ client: mockKnexClient.MockClient });
});
```

but then the next error appears:
`TypeError: Class extends value undefined is not a constructor or null`

What type of file does this library expect `../common/db-setup` from the example to be? I tried `export const db = knex(config);` and `export default knex(config);` but that doesn't seem to be it.

**Comment by felixmosh** [comment]
Thank you for opening this issue, I will fix the readme example.

It depends on what your mocked module (in your case it is ../../knex) exports.

can you share it?

**Comment by ashwinvandijk** [comment]
This is my `../../knex/index.ts`-file in full:

```import knex from 'knex';
import config from '../knexfile.js';

/**
 * Global is used here to ensure the connection
 * is cached across hot-reloads in development
 *
 * see https://github.com/vercel/next.js/discussions/12229#discussioncomment-83372
 */
// @ts-expect-error TS2339: Property 'mysql' does not exist on type 'Global & typeof globalThis'.
let cached = global.mysql;
// @ts-expect-error TS2339: Property 'mysql' does not exist on type 'Global & typeof globalThis'.
if (!cached) cached = global.mysql = {};

export function getKnex() {
    if (!cached.instance) cached.instance = knex(config);
    return cached.instance;
}

export default knex(config);
```

I added the default export and tried using that export in both my code and tests, but it doesn't work. Thanks for your effort!

**Comment by felixmosh** [comment]
If your production code uses `getKnex` function, your `jest.mock` should mimic it.

it should look like:
```js
jest.mock('../../knex/index.ts', () => {
  return {
    getKnex: () => {
      return knex({ client: MockClient });
    },
  };
});
```

As per `export default`, [jest docs specifies](https://jestjs.io/docs/jest-object) that you should mock it like this:
```js
jest.mock('./esModule', () => ({
  __esModule: true, // <-- this property is important
  default: knex({ client: MockClient }),
}));
```

**Comment by felixmosh** [comment]
What is your `knex` version?

**Comment by ashwinvandijk** [comment]
I've tried version `0.95.4` to `0.95.6`. Node is version `14.16.0`.

**Comment by felixmosh** [comment]
Weird, I'm using the same config.

Do you use TypeScript? if so, do you have `"esModuleInterop": true,` in your `tsconfig.json`?

**Comment by ashwinvandijk** [comment]
Yes I have. Here is my full tsconfig.json:
```
{
    "ts-node": {
        "compilerOptions": {
            "module": "commonjs"
        }
    },
    "compilerOptions": {
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext", "ESNext.Intl", "ES2018.Intl"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": false,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "jsxImportSource": "@emotion/react",
        "typeRoots": ["types", "node_modules/@types"]
    },

    "include": ["**/*.ts", "**/*.tsx"],
    "exclude": ["node_modules"]
}
```

**Comment by felixmosh** [comment]
From your error, looks like there is some issue with the default import of `knex`.

Can you put a console log in `./node_modules/knex-mock-client/dist/MockClient.js`.
```js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
...
console.log(knex_1.default) // these 2
console.log(knex_1.default.Client)

class MockClient extends knex_1.default.Client {
...
```

**Comment by ashwinvandijk** [comment]
I've added the console.logs. `knex` itself is defined, however `knex.Client` is not.

```
 console.log
    [Function (anonymous)]

      at Object.<anonymous> (node_modules/knex-mock-client/dist/MockClient.js:11:9)

  console.log
    undefined

      at Object.<anonymous> (node_modules/knex-mock-client/dist/MockClient.js:12:9)
```

I'll setup a test repo to make things a bit easier to debug.

**Comment by ashwinvandijk** [comment]
If I log `knex_1.default()`, as a function, I get the following result:

```
    {
      select: [Function: mockConstructor] {
        _isMockFunction: true,
        getMockImplementation: [Function (anonymous)],
        mock: [Getter/Setter],
        ...
      },
      from: [Function: mockConstructor] {
        _isMockFunction: true,
        getMockImplementation: [Function (anonymous)],
        mock: [Getter/Setter],
        ...
      },
      where: [Function: mockConstructor] {
        _isMockFunction: true,
        getMockImplementation: [Function (anonymous)],
        mock: [Getter/Setter],
        ...
      }
    }
```

**Comment by felixmosh** [comment]
Ha, looks you have another global mock for `knex` :]

**Comment by felixmosh** [comment]
Did you found the code that mocks knex?

**Comment by ashwinvandijk** [comment]
Sorry, yes I did. I feel kinda stupid now, but it works now :). It doesn't work with the getKnex-function, if I try to mock that I can't use the tracker. This isn't a big deal since I only need that in development. Thank you for your help!
