### ISSUE TITLE
Issues with simulateError()

### ISSUE THREAD

**Issue by brian-learningpool** [felixmosh/knex-mock-client#13]
I've noticed that if I call `simulateError()` it doesn't actually throw the error as expected.  The error message is prepended with the query.  

Also, it would be useful if `simulateError()` accepted both a message string and an instance of an Error.

**Comment by felixmosh** [comment]
Thank you for reporting this issue,
Can you share a code snippet that reproduces the issue?

What is your use case for needing to pass a custom error, (think of that, custom error means you are exposing internals).

**Comment by brian-learningpool** [comment]
Hi @felixmosh, thank you for getting back to me. 

I've swapped out using a Jest `__mocks__` folder to using `knex-mock-client` in a suite of unit tests, similar to the snippet below:

```
  const name: string = JSON.parse(event409.body).name
  const errorMessage: string = `Duplicate entry '${name}' for key 'name'; Error code: 1062; SQLState: 23000`
 
  tracker.on.insert(Constants.TableSchemas.CustomerAccounts)
    .simulateError(errorMessage)
   
  const response = await lambdaHandler(event409, context)

  expect(typeof response).toBe('object')

  expect(response.statusCode).toBe(409)
  const body = JSON.parse(response.body)

  expect(body.message).toBe(`'name' of '${name}' already exists`)
```

Unfortunately the error message is being thrown with the query at the start, for example:
```
insert into "customer_accounts" ("created_by", "max_seats", "name") values (1, 30, 'Existing customer') - Duplicate entry 'Existing customer' for key 'name'; Error code: 1062; SQLState: 23000
```

Which means that code in the `lambdaHandler` can't parse it correctly. 

The use case for a custom error (in our case we're just attaching a `code` property to `Error`) is that we have code to run with handled errors (HTTP 409s, etc.) and a different HTTP 500 response for unhandled errors.

**Comment by brian-learningpool** [comment]
You're right, it is `knex` itself.  Thanks for your help.
