### ISSUE TITLE
Doesn't support onConflict

### ISSUE THREAD

**Issue by chrisharrison** [felixmosh/knex-mock-client#15]
Given this code:
```
describe("on conflict", () => {
  const mockedKnex = knex({ client: MockClient, dialect: "pg" });
  let tracker: Tracker;

  beforeAll(() => {
    tracker = getTracker();
  });

  afterEach(() => {
    tracker.reset();
  });

  test("it mocks correct on conflict SQL", async () => {
    await knex("a_table")
      .insert({id: 1234, created_at: "2022-05-10", updated_at: "2022-05-10"})
      .onConflict("id")
      .merge(["id", "created_at"]);
  });

  console.log(tracker.history.insert);
});
```

The SQL logged is:
`insert into "a_table" ("created_at", "id", "updated_at") values (?, ?, ?)`

It should be something along the lines of:
`insert into "a_table" ("created_at", "id", "updated_at") values (?, ?, ?) on conflict ("id") do update set "id" = ? "updated_at" = ?`

**Comment by felixmosh** [comment]
I've tested it, and it works for me.
This is what I get
```js
[
  {
    method: 'insert',
    options: {},
    timeout: false,
    cancelOnTimeout: false,
    bindings: ['2022-05-10', 1234, '2022-05-10'],
    __knexQueryUid: 'Aq0oFojeAAX0hQJ6zb_r5',
    sql: 'insert into "table_name" ("created_at", "id", "updated_at") values (?, ?, ?) on conflict ("id") do update set "id" = excluded."id", "created_at" = excluded."created_at"',
    returning: undefined,
    queryContext: undefined,
  },
]
```

**Comment by alexedwardjones** [comment]
Just a heads up I have exactly the same issue as @chrisharrison for an insert/on conflict/merge.

**Comment by felixmosh** [comment]
> Just a heads up I have exactly the same issue as @chrisharrison for an insert/on conflict/merge.

Can you share a query?

**Comment by alexedwardjones** [comment]
```
const result = await this.knex
  .insert({
    id: user.id,
    name: user.name,
  })
  .into("user")
  .onConflict("id")
  .merge(["name"])
  .returning([
    "id",
    "name",
  ]);
```

**Comment by felixmosh** [comment]
Did you checked my [comment link](https://github.com/felixmosh/knex-mock-client/issues/15#issuecomment-1122361565)?
You need to specify the [`dialect`](https://github.com/felixmosh/knex-mock-client/blob/5efcfe3f0db550137f9ae52b599e5dbbf1a9c0cc/tests/dialects.spec.ts#L13) since `onConflict` is relevant only to postgress.
Hope this solves your issue.

**Comment by alexedwardjones** [comment]
My bad, I missed that you had specified the dialect. Thanks for your help 😄
