### ISSUE TITLE
Is this replaceable as mock-knex library ?

### ISSUE THREAD

**Issue by mir1198yusuf** [felixmosh/knex-mock-client#17]
- Is this library same as https://github.com/jbrumwell/mock-knex ? I have seen your comment https://github.com/jbrumwell/mock-knex/issues/109#issuecomment-841668270 so I wanted to enquire about that. `mock-knex` is not updated for knex 1.x & 2.x .

- What are major differences with `mock-knex` ? If not much, I will be happy to move to this lib.

- Is TypeScript supported ?

**Comment by felixmosh** [comment]
This lib is not the same as `mock-knex`, it is not a mock for knex, but it is a mock client of `knex` which is a different approach to the problem.

Think of that, `knex` is really complicated sql builder, and it supports out of the box multiple dialects (which is implemented as knex clients). 
This lib is a mock knex client which allows you to intercept the "final request" to the DB (no requests are emitted).

As I've written in the Readme, this lib is heavily inspired by [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter)

This new approach allows me to keep up with `knex` changes much easily since the "final request" that passed to the mock client is eventually some basic sql.
Which is not true for `mock-knex` which tries to mock knex's api.

**Comment by mir1198yusuf** [comment]
Thanks for the quick & elaborate response. However, due to my lack of understanding, I am still confused.
Sharing below some points, please confirm if they are correct.

- `knex-mock-client` is another knex client like existing `pg`, `mysql` but this is a mock client obviously. Using dialect example `pg`, this mock client becomes similar to actual `pg` knex client.
- So the way request are passed to actual knex clients, request are also passed to this mock knex client. Since this final request is raw sql generated by `knex`, at your mock client, you can capture the raw sql query.
- So, tracker can get hold of the sql here & can also return pre-determined response.
- So this library gets the request at mock client end.

If the above is correct, please confirm below doubts of how `mock-knex` is working so the difference is clear.
- As you mentioned, `mock-knex` tries to mock `knex` itself (like for example jest can mock a particular module crypto, so we determine the implementations of function within crypto module & actual module is never called)
- Then it is like the request never goes to the client end (in your library it goes atleast to the mock client end). 

Some doubts : 
1. If `mock-knex` is mocking only knex, but in actual usage of this library, we are not changing implementation or spying on any of `knex` library functions. We are similar to usage of this library, tracking the actual sql query. How `mock-knex` understands that a particular sql query is used? It does not have mock client end like in your library to check the request at end. Or does it recognise the sql query as soon as `knex` converts it to sql ?

PS- Sorry for some laymen descriptions of stuff and not actual definition as it helps understand better.

**Comment by mir1198yusuf** [comment]
> In other words, tracker of your library tracks sql at mock client end & where the tracker of mock-knex tracks the sql as it has no mock client ?

Update - I got some hint going through source code of `mock-knex`. It tracks when `knex`'s query method is called.

Do correct me if I am wrong.

**Comment by felixmosh** [comment]
Your observations are correct 💯,
I'm providing a small and minimum mock client so knex will work and pass the end request to the tracker.

**Comment by mir1198yusuf** [comment]
Ok. will try to use this lib as it supports the requirements.

**Comment by felixmosh** [comment]
Let me know if you encounter any bug / issue. :]

**Comment by mir1198yusuf** [comment]
My knex is 1.xx

Getting this error
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: knex@1.0.7
npm ERR! node_modules/knex
npm ERR!   knex@"^1.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^2.0.0" from knex-mock-client@1.8.0
npm ERR! node_modules/knex-mock-client
npm ERR!   dev knex-mock-client@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Should i use `npm i --save-dev knex-mock-client@1.6.2` ? It worked correctly

**Comment by felixmosh** [comment]
You can use older version of the lib, no problem
