### ISSUE TITLE
Add an on "create" handler?

### ISSUE THREAD

**Issue by SomethingSexy** [felixmosh/knex-mock-client#2]
Trying to test a query with 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'.  Looks like the rawQuery is coming in as 

```
      {
        method: 'create',
        sql: 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"',
        bindings: [],
        options: {},
        __knexQueryUid: 'YWbkHLXSCbrMkF-4EbyRi',
        queryContext: undefined
      }
```

But I think we would need a create method added to tracker.on to support this.  Or is there another way to handle this?

**Comment by felixmosh** [comment]
Since it is `Postgres` specific query, I don't think that the tracker should have `create` handler.

Maybe it is better to add `any` handler which these handlers will be used for any type of queries.
WDYT?

**Comment by felixmosh** [comment]
In `v1.4.0` there is a new `any` method which capture any query type.
Usage will look like:

```js
const affectedRows = 1;
tracker.on
  .any((rawQuery) => rawQuery.method === 'create' && rawQuery.sql.includes('"uuid-ossp"'))
  .response(affectedRows);
```
