### ISSUE TITLE
Objection.js upsertGraph is not captured properly

### ISSUE THREAD

**Issue by mir1198yusuf** [felixmosh/knex-mock-client#27]
The `upsertGraph` method basically inserts the objects where `id` is missing & updates the objects where `id` is present.

I am passing an object in `upsertGraph` with `id` present, it does captures `update` query, instead a `select` query is captured which selects all fields and has bindings on all key columns.

Same happens if I pass object without `id`. No `insert` query detected. Only `select` same as mentioned above.

Thanks.

**Comment by felixmosh** [comment]
Can you add a query for example?

**Comment by mir1198yusuf** [comment]
Query
```
const response = await AbcModel.query(trx)
            .upsertGraphAndFetch([{id:1, x: 1}, {x:2}], {noDelete: true, relate: true, update: true, insertMissing: true})
            .returning('id');
```

What is captured in MockClient
```
select "abc"."id", "abc"."x" from "abc" where ("abc"."id") in (($1)) 
```

Even if I removed `returning`, I get the same capture.

**Comment by felixmosh** [comment]
I've missed the fact that your issue is related to `Objection.js`, this lib is a mock for **Knex**.
I don't know, and not familiar with it... the [implementation](https://github.com/Vincit/objection.js/blob/23ce2af9efa1f75ba2d5a1c0f3fcd14de857553d/lib/queryBuilder/QueryBuilder.js#L691) of `upsertGraphAndFetch` is not straightforward, therefore, If you want my help with this, please provide a small repo that reproduces the issue you have. (It can be just a small node file).

**Comment by mir1198yusuf** [comment]
Ok, I will provide that but it would need one table migration file also right ?
or you need just a simple file with mock client ?

(I said table file in 1st point because you might need to compare the actual behaviour with mock behaviour of `upsertGraph`)

**Comment by felixmosh** [comment]
simple file with the mock ...

**Comment by mir1198yusuf** [comment]
https://github.com/mir1198yusuf/objectionjs-test-repo.
I am getting this error `Trying to access tracker before knex initialized`.

Some small mistake I am unable to figure out

**Comment by felixmosh** [comment]
Check my pr
https://github.com/mir1198yusuf/objectionjs-test-repo/pull/1

**Comment by mir1198yusuf** [comment]
I tested this, working fine.
The flow was as you mentioned : 
select => insert/update => select (last select if `upsertGraphAndFetch` used)
