### ISSUE TITLE
Document that the .response() and .responseOnce() methods can take an (async) callback

### ISSUE THREAD

**Issue by aryehb** [felixmosh/knex-mock-client#28]
The `.response()` and `.responseOnce()` methods can take an (async) callback, and the result of the callback will be returned as the result of the query, as can be seen [here](https://github.com/felixmosh/knex-mock-client/blob/aa84c20809291974260bbc3aec9005a01c38d889/src/Tracker.ts#L64-L65). However, this is not documented in the README.

**Comment by felixmosh** [comment]
Do you want prepare a PR for this?
