### ISSUE TITLE
Returning automatically added in insert queries

### ISSUE THREAD

**Issue by mir1198yusuf** [felixmosh/knex-mock-client#29]
Hello,

`returning` is auto-added in `insert` queries.
It is not added for `update` queries which is expected.

Is `returning` addition expected way as I could not find any hints to it from knex docs ?

**Comment by mir1198yusuf** [comment]
Please check the logs of `Test 1` for issue replication.
https://github.com/mir1198yusuf/objectionjs-test-repo

**Comment by felixmosh** [comment]
This probably how objection implements `upsertGraph` internally. Not related to this lib.

**Comment by mir1198yusuf** [comment]
This happens with normal `insert` too. (not within `upsertGraph`).
Is this also related to objection ?

**Comment by felixmosh** [comment]
yeap...
