### ISSUE TITLE
Add a property to the tracker history to track all queries in order

### ISSUE THREAD

**Issue by aryehb** [felixmosh/knex-mock-client#32]
Currently, the tracker history is split up by method (e.g. `tracker.history.select`, `tracker.history.insert`). It appears to me that there's no built-in way to get a list of all queries in the order that they were run.

I think it would make sense to add something like `tracker.history.all`, which would be a list of all queries.

**Comment by felixmosh** [comment]
What is the use case that you've stumbled with?

**Comment by aryehb** [comment]
I'm writing tests for code that runs a number of queries, and I want to be able to check that they were run in the correct order.

**Comment by aryehb** [comment]
True. However, when mocking a DB it's hard to objectively check the outcome, since it's there's no actual state, and the outcome is based on what the mock returns.

For example, if you have a function that updates a row and then selects it, when running integration tests with an actual DB, all you have to do is check that the function returns the updated data, and optionally check that the row was actually updated in the DB.

However, when mocking the DB with something like this:
```js
tracker.on.update('update my_table set val = ? where id = ?').response(1);
tracker.on.select('select * from my_table where id = ?').response([{ id: 1, val: 2 }]);
```
The second handler will return the updated data regardless of the actual order the queries were run, and there's no canonical state to check to see if it was updated.

If the code mistakenly got changed from:
```js
async function update() {
  await knex('my_table).update({ val: 2 }).where('id', 1);
  return knex('my_table).where('id', 1);
}
```
to
```js
async function update() {
  const result = await knex('my_table).where('id', 1);
  await knex('my_table).update({ val: 2 }).where('id', 1);
  return result;
}
```
When running integration tests that use an actual DB, the test would fail, since the function would return the old value. However, when mocking as above, the function will return the updated value regardless, and there would be no way to test for this.

**Comment by felixmosh** [comment]
Ham, you did convinced me...
Actually there is such support already when using all scope...
It will register the calls with by the call order.
But i guess that this is not so convenient.
Let me think about a proper solution for this one.

**Comment by aryehb** [comment]
See #33 for what I was envisioning.

**Comment by felixmosh** [comment]
I think that in test that you need to check the order you can use `any` statement which supports all types.

**Comment by felixmosh** [comment]
@aryehb, does it solves your requirement?

**Comment by felixmosh** [comment]
Ping?

**Comment by aryehb** [comment]
Sorry for the delay.

[This](https://github.com/felixmosh/knex-mock-client/pull/33#issuecomment-1321289701) comment from @Fryuni sums up my response.

Using `history.any` would require using `tracker.on.any()` for all mocks, and would preclude using any of the other methods (e.g. `tracker.on.select()`).
