### ISSUE TITLE
ReferenceError: Cannot access 'knex_1' before initialization

### ISSUE THREAD

**Issue by zagumaar** [felixmosh/knex-mock-client#39]
Hi !
I wanted to try your library to mock the knex client in my app so I setup a basic test but I have this error right at the start, an idea why ?
```shell
ReferenceError: Cannot access 'knex_1' before initialization

      jest.mock('../../drivers', () => {
        return {
          db: knex({ client: MockClient })
               ^
        };
      });
```

My code so far : 

```javascript
import {MyRepository} from '@infra';
import knex, {Knex} from 'knex';
import {getTracker, MockClient, Tracker} from 'knex-mock-client';

jest.mock('@infra/drivers', () => {
  return {
    client: knex({
      client: MockClient,
    }),
  };
});

describe('MyRepository', () => {
  let myRepository;

  beforeAll(() => {
    myRepository = new MyRepository();
    tracker = getTracker();
  });

  afterEach(() => {
    tracker.reset();
  });

  it('should be instantiated', async () => {
    expect(myRepository).toBeInstanceOf(MyRepository);
  });
});
```

**Comment by felixmosh** [comment]
Hi @zagumaar , from your error, looks like you have a setup error.
Probably related to the way you are importing `knex`.

Try to console.log(knex) after the import, check if you get the constructor.
Try to import knex with asterisk.
```js
import * as knex from 'knex';
```

**Comment by bmxpiku** [comment]
I'm facing the same error, and when importing with asterisk now error is:
```
 Type 'typeof import("/home/pkurek/workspace/bm.ms.auth_service/node_modules/knex/types/index")' has no call signatures.

```

**Comment by felixmosh** [comment]
Do you able to print `knex` value? maybe it has a `default` property, and you should access it as
```js
knex.default({client: MockClient});
```

Anyway, it is not related to this lib, it is an issue with typescript & jest setup. (you can validate this by removing Mock lib entirely from the file, it will fail as well.)

Can you prepare a small reproduction repo, which I will be able to inspect?

**Comment by bmxpiku** [comment]
I'll try, but first I'll try to go around it using  __mocks__ , I'll post reproduction repo if this approach will fail.

**Comment by felixmosh** [comment]
@zagumaar can you create a small repo that reproduces your issue?

**Comment by felixmosh** [comment]
Any update?

**Comment by zagumaar** [comment]
Sorry I was really busy, I will try to create a new repo see if I have the issue, I tried it first in the context of a bigger project so maybe that's why I had the error.

**Comment by bmxpiku** [comment]
and I simplified my approach within unit tests - and within `__mocks` directory I added
```
export const queryBuilder = jest.fn();
```
and then within tests
```
jest.mock('@src/clients/knexInstance');
(queryBuilder as jest.Mock).mockReturnValue({
      insert: jest.fn().mockReturnThis(),
      returning: jest.fn().mockReturnValue([client]),
    });
```
it was enough for me.

**Comment by felixmosh** [comment]
@bmxpiku, your approach mocks knex itself, if it works for you, then great :]

**Comment by zagumaar** [comment]
Alright sorry for the long delay,
I managed to make it work by using something like that :

```javascript
import {MyDriver} from '@infra/driver';

jest.mock('@infra/drivers', () => {
  const knex = require('knex');
  const { MockClient } = require('knex-mock-client');
  return {
    MyDriver: { client: knex({ client: MockClient }) },
  };
});
```

Just had to require what I needed inside this code block
