### ISSUE TITLE
Why should we use "knex-mock-client" over traditional mocking?

### ISSUE THREAD

**Issue by advename** [felixmosh/knex-mock-client#40]
I've come across this library, and aswell [`mock-knex`](https://github.com/jbrumwell/mock-knex), but fail to find any only resource that mentions why this library might be advantageous over traditional mocking in, lets say, jest with `jest.mock` or `jest.spyOn`?

Also, what is the difference between this library and `mock-knex`?

**Comment by felixmosh** [comment]
Actually this lib was created when I was looking for unit test my controllers with DB access.
At the time, `mock-knex` supported only the old version of `knex`, this emphasis you the benefit of this lib.
While `mock-knex`  mocks the interface of `knex` api, therefore, each time `knex` adds (changes) it api, the mock should follow.

With this lib approach, it implements the mock as a valid Knex adapter (knex supports mysql, postgress, sqlite and more...), which doesn't require me to "add" support for the new knex api. (for example, it added Mysql Json api recently, and I didn't need to add one line of code to support it :] )

Hope this make sense.

**Comment by advename** [comment]
So, what you're trying to say is that `knex-mock-client` uses a different approach, that doesn't break that easily on updates compared to `mock-knex`?

And about the why use `knex-mock-client` over `jest.mock`?

**Comment by advename** [comment]
I fully understand what `jest.mock` does in Jest tests.

What I'm trying to understand here is why I should use `knex-mock-client` instead of mocking modules with jest, without this dependency.

**Comment by felixmosh** [comment]
This mock client allows you to run a real knex, without connecting to real db.
You can mock knex yourself, this lib provides you utilities like history tracking, query matchers and more.
You can simulate errors, simulate responses. It supports matchers for multiple requests & responses.

You can do it with jest.mock, but it will be more tedious.

**Comment by advename** [comment]
I see, `knex-mock-client` is basically a library that provides common mocking utility functions on top of knex for testing.
