### ISSUE TITLE
Document breaking changes (`getTracker` is gone in v2.0.0)

### ISSUE THREAD

**Issue by grahamb** [felixmosh/knex-mock-client#43]
Version 2.0 removes the `getTracker` named export. This is a breaking change and isn't documented anywhere in the release notes or readme. 

Looking at the diff for 037ec06cd30e5489381273c6d2660b1a7a95a1e1, I guess we're supposed to use `createTracker` now instead of `getTracker`? It looks like `createTracker` now expects to be passed a knex instance, unlike `getTracker`. This is breaking my tests; I'm using Objection.js models, so the models already have a reference to the knex instance, which in `NODE_ENV=test` is configured to use the `MockClient`:

knexfile.js:
```js
import dotenv from 'dotenv';
import { MockClient } from 'knex-mock-client';
import { knexSnakeCaseMappers } from 'objection';
const configPath = new URL('../../.env', import.meta.url).pathname;
dotenv.config({ path: configPath });

const {
  NODE_ENV,
  PG_DB_HOST,
  PG_DB_PORT,
  PG_DB_USER,
  PG_DB_PASSWORD,
  PG_DB_DATABASE,
  PG_DB_APPLICATION_NAME = '',
} = process.env;

export const pgDbConfig =
  NODE_ENV === 'test'
    ? {
        client: MockClient,
        dialect: 'pg',
        ...knexSnakeCaseMappers(),
      }
    : {
        client: 'pg',
        migrations: {
          stub: 'migrationTemplate.js',
          directory: 'migrations',
        },
        connection: {
          host: PG_DB_HOST,
          port: PG_DB_PORT,
          user: PG_DB_USER,
          password: PG_DB_PASSWORD,
          database: PG_DB_DATABASE,
          application_name: PG_DB_APPLICATION_NAME,
          ssl: false,
        },
        ...knexSnakeCaseMappers(),
      };
```

My test file, pre 2.0:

```js
import { getTracker } from 'knex-mock-client';
import t from 'tap';
import validRegistrationTypesForUser from '../validRegistrationTypesForUser.js';

let tracker = getTracker();

// ... tests follow, using the tracker to intercept queries and return mock results

```

**Comment by felixmosh** [comment]
You are correct, v2 is a major version which means that it has a breaking change.

I'm not familiar with objection.js, can you get the knex instance out of it?

**Comment by felixmosh** [comment]
I'm closing this issue since there is no real reason for it, feel free to re-open.
