### ISSUE TITLE
Getting "TypeError: db.client.setTracker is not a function"

### ISSUE THREAD

**Issue by kevbahia** [felixmosh/knex-mock-client#44]
Hi, I have created a sample unit test using knex 2.4.2 and knex-mock-client 2.0.0 however upon running the unit test, I'm getting the type error:

![image](https://user-images.githubusercontent.com/16178884/235900385-6b53a783-3078-4293-bb38-f96f06a2acdf.png)

Here's my sample unit test:

![image](https://user-images.githubusercontent.com/16178884/235900694-564ed8df-3e16-4726-ba95-03e6d1cc5bc1.png)

I haven't added a test yet because I'm trying to isolate the issue and this is my database/index:

![image](https://user-images.githubusercontent.com/16178884/235901042-3462b8ff-7a0a-4e8d-b9cd-a5cf32b665a5.png)

I have also tried to make it a named export just like in the readme file but still getting the same error. Any thoughts?

**Comment by felixmosh** [comment]
Hi @kevbahia, can you share you sample repo?

**Comment by kevbahia** [comment]
Unfortunately, I wasn't able to share this exact repo because it's a client code. What I did instead is I tried to replicate this on a sample app but then I'm getting a different error. [here is the link](https://github.com/kevbahia/knex)

**Comment by felixmosh** [comment]
From this repo looks like it is an issue with setup of jest mocks... (esm modules)

I'm not using esm, so I can't really help you.
You can check the `db.client` field, it should be `MockClient`

**Comment by felixmosh** [comment]
Following [this blog post](https://www.sitepen.com/blog/jest-esm-almost-there) there are 2 things that should be changed,
1. using `jest.unstable_mockModule` instead of `jest.mock`
2. importing `knex` lib with `import()`
3. importing the mocked module **after** the mocking (because jest not hoisting the mock as it does with cjs)

```js
import { jest } from "@jest/globals";
import { createTracker, MockClient } from "knex-mock-client";

jest.unstable_mockModule("../src/database/index.js", async () => {
  const knex = await import("knex");
  return {
    db: knex.default({ client: MockClient }),
  };
});

describe("sample service", () => {
  let tracker;

  beforeAll(async () => {
    const { db } = await import("../src/database/index.js");
    tracker = createTracker(db);
  });

  it("should pass with valid data", async () => {
    
  });
});
```

This snippet works without errors.

**Comment by kevbahia** [comment]
Hi @felixmosh, I tried the snippet you have mentioned and it works! I can proceed now with my unit tests using knex-mock-client. Thanks! 😄
