### ISSUE TITLE
Getting "Tracker not configured for knex mock client" error when running unit test

### ISSUE THREAD

**Issue by karenm1895** [felixmosh/knex-mock-client#45]
Hi, we are trying to set up knex mock client in our unit test but unfortunately we are getting the error message "Tracker not configured for knex mock client". To be specific when we run it for the first time, the test would pass then running it for the second time, it would get the error message above. The test result would alternate as we continue to run it.

Here is the error from jest:
![image](https://github.com/felixmosh/knex-mock-client/assets/91040480/29b9f56e-a874-46f9-bb01-dbc4aacfda78)

Here's our knex set up:
![image](https://github.com/felixmosh/knex-mock-client/assets/91040480/d6c5c223-1faf-4700-bc74-0494651364e4)

Here's our sample unit test:
![image](https://github.com/felixmosh/knex-mock-client/assets/91040480/7165799c-a9cb-4b5d-ab54-46c4dcab9f0c)

Do you have any thoughts with this issue? Thanks!

**Comment by felixmosh** [comment]
The code looks ok, probably there is something that resets the setup of the tracker,

Try to mock the tracker creation to a `beforeEach` section

**Comment by karenm1895** [comment]
Hello Felix, we tried moving the creation of the tracker inside beforeEach and we got the same error
![image](https://github.com/felixmosh/knex-mock-client/assets/91040480/665278e0-b12f-4536-b2f8-ee3deee18059)

We also tried putting the test setup code inside the test itself, but got the same error.
![image](https://github.com/felixmosh/knex-mock-client/assets/91040480/c4e02dc1-5c53-4fb4-9d34-6577f6a78359)

**Comment by karenm1895** [comment]
Hi Felix, 
Unfortunately, we cannot replicate this behavior in our local repo and we cannot share our client repos. 

Our observation in our testing is when the controller runs first before the service we will get a fail and when the service runs first before the controller we get a pass, currently the sequence of how jest run the test in our code is random. 
With the observation we have above, we just added a workaround to use a test-sequencer to explicitly tell to run the services test before the controller and other test to have a pass in our unit test. 

Let me know if you have any idea why we're encountering that weird behavior or other suggestion we can try to fix it. Thanks!

**Comment by felixmosh** [comment]
Sounds like an issue with parallel run, you need to mock your db connection on every test that uses it.
It is not related to this lib at all...

In my project, I have a `createApp` function which will initiliaze all express routes and will return an Express app, this createApp gets the `db` instance.

So in production code I'm connecting to the real DB, in tests i', creating a new Knex instance with the mock client and passing it to the function, this way I don't need to use jest mock modules.
