### ISSUE TITLE
Usage alongside `knex-paginate`

### ISSUE THREAD

**Issue by rowbot-weisguy** [felixmosh/knex-mock-client#49]
Hi there, this library has immediately been very helpful for testing. However, I have one gap that I'm not sure how to address since it crosses the boundaries of multiple packages - `knex`, `knex-paginate`, and this `knex-mock-client`. I'm currently skipping tests that use pagination until I can figure out a solution.

In our app we've augmented the `knex` client with `knex-paginate`, which adds a `.paginate` method to the query builder. 

When I use this client, it fails on `.paginate` calls, and since `knex-mock-client` is doing the mocking, I'm not sure how to add to that properly in order to support this `.paginate` method. 

Here's what I tried in my `setupTests.ts` file for jest:

```
jest.mock("./db", () => {
  const _knex = require("knex");
  const client = _knex({ client: MockClient, dialect: "pg" });
  client.paginate = jest.fn().mockReturnValue(client);
  return {
    knex: client,
  };
});
```

Do you have any ideas for how to do this correctly?

**Comment by rowbot-weisguy** [comment]
Oh! I just realized you wrote `knex-paginate` too, @felixmosh. 😆 Hopefully this is a familiar need then!

**Comment by rowbot-weisguy** [comment]
I've found one possible solution using `patch-package` to patch `knex-mock-client`. 

Instead of trying to mock it in my jest setup, I have instead modified `knex-mock-client/dist/MockClient.js`:

```diff
const knex_1 = __importDefault(require("knex"));
+ const knexPaginate = require("knex-paginate");
const MockConnection_1 = require("./MockConnection");
+ knexPaginate.attachPagination();
class MockClient extends knex_1.default.Client {
```

And then my `setupTests.ts` file is back to simple documented settings:
```
jest.mock("./db", () => {
  const knex = require("knex");
  return {
    knex: knex({ client: MockClient, dialect: "pg" }),
  };
});
```

**Comment by felixmosh** [comment]
Yeah, it is not related to the client-mock... This it the beauty of the approach that mock-client uses, it mocks the client to the db, it doesn't touches the queryBuilder at all... 
Glady libs are useful to you 🙏🏼
