### ISSUE TITLE
Consecutive response() calls for the same query

### ISSUE THREAD

**Issue by scarabcoder** [felixmosh/knex-mock-client#50]
Hi,
Is there an easy way to mock the response to consecutive calls using the same query?

If I have this query matcher for selects to the users table:
```TypeScript
tracker.on.select('users').response({id: 2})
```

And if the query was being called twice in the unit I'm testing, how would I have it return a different item for the second call?

Currently what I'm doing is passing `jest.fn()` into the `response()` tracker function, then using Jest's chained `mockReturnValueOnce` to respond with different values. However, it would be nice if there were a way to to that directly with this library, such as chaining `responceOnce()` methods together. 

Thank you!

**Comment by felixmosh** [comment]
Actually this lib supports that,
```js
tracker.on.select(X)
```
supports:
1. strings - matches by string contains
2. regex 
3. custom matcher

So you can either check with a `string` and full query (where).
In your case, I think that `custom matcher` will be suitable,
```js
tracker.on
  .select(
    ({ method, sql, bindings }: RawQuery) =>
      method === 'select' && /^from `users` where `id`=1/.test(sql)
  )
  .response({ id: 1, name: 'user 1' });

tracker.on
  .select(
    ({ method, sql, bindings }: RawQuery) =>
      method === 'select' && /^from `users` where `id`=2/.test(sql)
  )
  .response({ id: 2, name: 'user 2' });
```

**Comment by scarabcoder** [comment]
@felixmosh Thanks, that works for two different queries. My case specifically is a get-or-insert type function, where it may do a SELECT -> INSERT -> SELECT, with both select queries being identical but the first one returning an empty response [].
I realize I could use a custom function to return the different responses (which is what am achieving now with `jest.fn()`)

**Comment by felixmosh** [comment]
Yeap, response can get a function, there you can make any logic you want
