### ISSUE TITLE
Detect transaction rollbacks

### ISSUE THREAD

**Issue by scarabcoder** [felixmosh/knex-mock-client#51]
Apologies if this is already a feature/documented, but I couldn't find it.
I'm trying to assert that an database insert/modification did not happen because it was rolled back.
`Tracker.history.insert` shows rolled back inserts, so I'm wondering if there is an alternative way to determine if something was rolled back?

**Comment by felixmosh** [comment]
Yes you can, by inspecting the `tracker.history.transactions` field, which contains all transactions + it statuses.
Check the [test code](https://github.com/felixmosh/knex-mock-client/blob/master/tests/transaction.spec.ts#L66)
