### ISSUE TITLE
Module not found with v3.0.0

### ISSUE THREAD

**Issue by eva-ortuno** [felixmosh/knex-mock-client#54]
Following the release of v3.0.0, I updated it in my repo. It seems to me that there is no breaking changes that need to be tackled in the implementation of the tests. However I am receiving the following error : 
![image](https://github.com/felixmosh/knex-mock-client/assets/90448715/082cf9e0-409b-425e-a19b-47bb762ccaa9)

As there is no "types" package, I suppose there must be some issue on the package itself.

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue, looks like I've missed decleration files.

The fix released in `v3.0.1`

**Comment by eva-ortuno** [comment]
That was really fast ! Thanks a lot. I tested it and it works now 👍
