### ISSUE TITLE
Doesn't support distinctOn and other database specific methods

### ISSUE THREAD

**Issue by ZeRego** [felixmosh/knex-mock-client#7]
Note that I'm going to talk about the distinctOn method but there are others methods in the same situation.

We are using [distinctOn](https://knexjs.org/#Builder-distinctOn) which is only supported for Postgres. 

I get the error: 
```
'.distinctOn() is currently only supported on PostgreSQL'
```

This is because the mock client extends the basic knex client. This client uses the basic query compiler, that has the implementation:

```
  // node_modules/knex/lib/query/querycompiler.js
  distinctOn(value) {
    throw new Error('.distinctOn() is currently only supported on PostgreSQL');
  }
```

Work around I found for this problem: 

```
class MockClientWithDistinctOn extends MockClient {
    queryCompiler(builder: any) {
        const queryCompiler = super.queryCompiler(builder);
        queryCompiler.distinctOn = (value: any) => '';
        return queryCompiler;
    }
}

...
const database =  knex({ client: MockClientWithDistinctOn }
```

Maybe we could have a MockClient for each supported client. If this is to much we could just return an empty string for these methods.

**Comment by felixmosh** [comment]
I need to check for possible solutions... 
I don't want to stub each one of the specific functions.

**Comment by felixmosh** [comment]
Added in `v1.6.0`, thank you for reporting this issue, now the lib supports a specific dialects :]
