### ISSUE TITLE
Error: SAVEPOINT trx2; - No mock handler found

### ISSUE THREAD

**Issue by ZeRego** [felixmosh/knex-mock-client#8]
When I'm using nested transactions I get the following error:

```Error: SAVEPOINT trx2; - No mock handler found```

I tried adding 'SAVEPOINT' to `transactionCommands` without success.

**Comment by felixmosh** [comment]
I need a simple reproduction code.

**Comment by ZeRego** [comment]
Here is a unit test with the error
```
  it('should support nested transactions', async () => {
    tracker.on.insert('table_name').responseOnce(1);
    tracker.on.delete('table_name').responseOnce(1);

    await db.transaction(async (trx) => {
      await db('table_name').insert({ name: faker.name.firstName() }).transacting(trx);
      await trx.transaction(async (innerTrx) => {
        await db('table_name').delete().where({ name: faker.name.firstName() }).transacting(innerTrx);
      });
    });

    expect(tracker.history.insert).toHaveLength(1);
    expect(tracker.history.delete).toHaveLength(1);
  });
 ```
 
 I'm wondering if nested transactions are an anti-pattern and I need to change my code to not have them. I didn't know about the `.transacting()` method so I'm going to try to refactor my code to have a single transaction.

**Comment by felixmosh** [comment]
If knex allows it, it should work with mock-client as well.

I guess that it should be part of the transaction commands.

**Comment by felixmosh** [comment]
Added in `v1.6.0`, thank you for reporting this issue 🙏🏼
